// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8cr25dvSVg9Wcku5aJRXWiQStdZpVamI',
    appId: '1:963921635993:web:762f75422bdbfe873de608',
    messagingSenderId: '963921635993',
    projectId: 'flutter-test-hientrn',
    authDomain: 'flutter-test-hientrn.firebaseapp.com',
    storageBucket: 'flutter-test-hientrn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirOpoydcuc7nRTroiJMxqA3XZZag_80g',
    appId: '1:963921635993:android:1df999e56f3d07da3de608',
    messagingSenderId: '963921635993',
    projectId: 'flutter-test-hientrn',
    storageBucket: 'flutter-test-hientrn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvZpZ0XjHUhwkWWW1d5BiZkQl7jqqeXMw',
    appId: '1:963921635993:ios:b6585ea8731fea9d3de608',
    messagingSenderId: '963921635993',
    projectId: 'flutter-test-hientrn',
    storageBucket: 'flutter-test-hientrn.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvZpZ0XjHUhwkWWW1d5BiZkQl7jqqeXMw',
    appId: '1:963921635993:ios:d8f454e25d01bebd3de608',
    messagingSenderId: '963921635993',
    projectId: 'flutter-test-hientrn',
    storageBucket: 'flutter-test-hientrn.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTest.RunnerTests',
  );
}
